version: '3.8'

services:
    db:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 0405
        POSTGRES_DB: dedservice
      ports: 
        - "5432:5432"
      restart: unless-stopped
